### ISSUE TITLE
Get links to apps on the homepage from JSON

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/core#37]
The liquid homepage should display links to the bundled apps:
* `http(s)://hoover.${liquid_domain}`
* `http(s)://dokuwiki.${liquid_domain}`
* `http(s)://rocketchat.${liquid_domain}`
* `http(s)://nextcloud.${liquid_domain}` (replaces davros)

For the previous iteration of liquid, this was implemented as a django settings file template: https://github.com/liquidinvestigations/setup/blob/master/ansible/roles/liquid-core/templates/local.py#L16-L34

I think we should keep the environment variable names and configure them via the nomad template: https://github.com/liquidinvestigations/node/blob/master/templates/liquid.nomad#L21-L31

**Comment by gabriel-v** [comment]
Most of this work is already done; but we should have a new environment variable called `LIQUID_APPS` that gets set to `hoover,rocketchat,dokuwiki,nextcloud` here: https://github.com/liquidinvestigations/node/blob/d37603ec0eb320b1cf8298f944af329aa4d34da2/templates/liquid.nomad#L37

The links should only appear on the home page if the service is listed in that variable.

**Comment by mgax** [comment]
> we should have a new environment variable called `LIQUID_APPS`

Let's think big. We need a list of links, app names, maybe even links to icons. So let's make a JSON file, either as environment variable, or as a separate file in `local/`. Then we can mess with the apps all we want without changing the code in liquid-core.

**Comment by mgax** [comment]
So [node](https://github.com/liquidinvestigations/node) should build a data structure like so:
```json
{
  "apps": [
    {"name": "Hoover", "url": "https://hoover.liquiddemo.org"}
  ]
}
```

Then, when rendering the `liquid-core` task, it should inject the data as JSON into a consul template named `local/apps.json` using Jinja's [json filter](http://jinja.pocoo.org/docs/2.10/templates/#tojson): `${ liquid_apps|tojson|safe }`.

Bonus points for investigating whether `|safe` is required. It's designed to disable html escaping. Maybe we can disable html escaping globally, because we're rendering hcl, not html.
